services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodeserver:0.0.2
    ports:
      - "8080:8080"
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: nginx:1
    ports:
      - "80:80"

  db:
    build:
      context: .
      dockerfile: Dockerfile
    image: postgres:17-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment: 
      # - POSTGRES_USER:admin
      # - POSTGRES_PASSWORD:qwe123
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
